### ISSUE TITLE
userContext menu inconsistent padding

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1306]
**Describe the bug**
the userContext menu menu entries have padding different from the header. I feel like the header has the visually better padding
![image](https://github.com/TUM-Dev/gocast/assets/64852250/b2d3caef-da58-4629-bced-816cb8395a1f)
the header has padding `0.5rem 1rem`, the menu entries have `0.5rem[ 0.5rem]`

**To Reproduce**
1. Go to Startpage
2. Click on the user icon at the top right

**Expected behavior**
![image](https://github.com/TUM-Dev/gocast/assets/64852250/47d52ff2-7b3d-4af7-b83d-acf0f7eecceb)
edited so that both the header and the entries have padding `0.5rem 1rem`

**Desktop (please complete the following information):**
 - OS: ubuntu 23
 - Browser: Firefox 121
 
 **Additional info**
 my browser shows me this in home.css in lines 2752-2755 and 2768-2775 respectively
 Frankly I couldnt find the culprit in the repo. Im _assuming_ its tailwinds
```css
.tum-live-menu>header {
  border-bottom-width:1px;
  padding:.5rem 1rem
}
```
 ```css
 .tum-live-menu .tum-live-menu-item {
  margin-top:.5rem;
  margin-bottom:.5rem;
  display:flex;
  width:100%;
  align-items:center;
  padding:.5rem /* this is the problem */
}
```
