### ISSUE TITLE
Make chat names distinguishable

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#256]
**Is your feature request related to a problem? Please describe.**
When there are many people in a chat room some people might have the same (first) name. This makes it hard to account a message to a person when there is name conflict.

**Describe the solution you'd like**
For example like Twitch we could assign every name with a random color, may it be really subtle/pale. Maybe a small icon could also be an option.

**Describe alternatives you've considered**
We could leave it like this. It looks definitely cleaner without any colors, like it is now. Alternatively, one could append the first letter of the last name.

**Additional context**
How [Twitch](https://twitch.tv) solves this:
![image](https://user-images.githubusercontent.com/30267166/150659982-398afa14-e5f5-4e25-9e29-3dec4321a2a9.png)

**Comment by joschahenningsen** [comment]
Tweedback assigns a random 6 digit number to every chat member, thoughts on this? Probably not as distinguishable as colors, but perhaps a little cleaner.

**Comment by alexanderstephan** [comment]
Hm, that would be a little bit verbose, but a possible solution. :+1: 
Twitch doesn't really look that aesthetic here, but I just checked this out in [Element](https://element.io/), and I think there it looks pretty good actually! Maybe we can do some math on how many colors prevent clashes >99,9% of the time.
YouTube randomly generates a small avatar for every participant, this would also maybe be an option.

**Comment by joschahenningsen** [comment]
Element/Matrix(?) seems to assign a random color from this set:
```css
.mx_Username_color1 {
 color:#368bd6
}
.mx_Username_color2 {
 color:#ac3ba8
}
.mx_Username_color3 {
 color:#0dbd8b
}
.mx_Username_color4 {
 color:#e64f7a
}
.mx_Username_color5 {
 color:#ff812d
}
.mx_Username_color6 {
 color:#2dc2c5
}
.mx_Username_color7 {
 color:#5c56f5
}
.mx_Username_color8 {
 color:#74d12c
}
```

Doing the same would make a clash (same name and color) very unlikely. But I don't know how intuitive this is to the readers. Another option would be to add the lrz id to the chat. This might be kind of confidential though.
